name: Delete data from ARCHE

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Delete data from ARCHE 
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: ${{secrets.ARCHE_USER}}
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-curation.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/ofmgraz
      TITLEIMAGE: https://id.acdh.oeaw.ac.at/ofmgraz/ofmgraz-titelbild.png

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: delete data
      run: ./arche__delete.sh
    
        
