name: ARCHE-Binaries-Import

on:
  workflow_dispatch

jobs:
  build_pages:
    name: Ingest Binary-Data into ARCHE
    runs-on: ubuntu-latest
    env:
      ARCHE_USER: ${{secrets.ARCHE_USER}}
      ARCHE_PASSWORD: ${{secrets.ARCHE_PASSWORD}}
      ARCHE: https://arche-curation.acdh-dev.oeaw.ac.at/api
      TOPCOLID: https://id.acdh.oeaw.ac.at/ofmgraz

    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Download arche.ttl
      run: ./dl_binaries.sh
    - name: run binaries import
      run: ./arche__ingest_binaries.sh
    
        
